### ISSUE TITLE
Do not assume location = keyboard layout

### ISSUE THREAD

**Issue by maxnet** [raspberrypi-ui/piwiz#1]
piwiz seems to assume that if you select Netherlands as country, you also have a nl keyboard layout.
While a NL layout existed in times mechanical typewriters were common, US layout is sold nowadays...

Also be aware that in some other countries -especially those that have more than one official language- multiple layouts exist.
Keyboard layout really should be a separate selection box (with a sensible default).

**Comment by spl237** [comment]
As I explained in the original blog post, there are going to be situations where the wizard will not cover all the options, and the user will need to fall back to using the full config dialog. The purpose of the wizard is to be as simple as possible and to cover a majority of users' needs - this entails compromises in not covering every possible option.

**Comment by maxnet** [comment]
Yes, I noticed you mentioning rare cases like expatriates in your blog post.
Just be aware that this affects more people than you may be thinking, and affects entire countries.

**Comment by spl237** [comment]
There is no point in expanding the wizard to cover all cases - it then becomes a duplicate of the horrendously messy Linux localisation settings, which is the thing it was set up to avoid. I am aware that there are going to be issues with it for some people, but as soon as I try to cover them, I end up back where I started... At worst, after running the wizard, some people will need to go and make some localisation changes, which they would probably have had to do anyway if the wizard hadn't been there.

**Comment by maxnet** [comment]
Well, if you do not want the extra selection box, can't you do some attempt at mapping the default layout to a better value?
Country NL -> US layout
(that would at least fix the problem for NL, as US layout is the only one used nowadays.
but obviously will not solve the problem for countries that have multiple languages and layouts like Canada)

P.S. your blog spam filter doesn't seem to let me reply to your post anymore.
But as far as setting overscan dynamically goes, there is a mailbox property called "Set overscan": https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface
Also see: https://github.com/ukscone/set_overscan
Probably also need to let X know resolution has changed.

**Comment by btjsteens** [comment]
Yes, please us US International layout for Dutch as default.
No one uses keyboards with a Dutch layout.
