### ISSUE TITLE
Annoying audio prompt about installing a screen reader

### ISSUE THREAD

**Issue by tenbob** [raspberrypi-ui/piwiz#18]
After boot  I hear a repetitive audio message that says something like "To install a screen reader press Ctrl+Alt+K". This repeats every 15 seconds. It loops forever and there is no obvious way to turn it off. 

It goes without saying that this is extremely annoying. It prevents any normal use of the sound system. I am unable to do whatever it wants me to because it's a headless system without a keyboard. In fact, the recording is of such poor quality that it's hard to tell what it is saying. One user thought it was  Ctrl+Alt+SPACE. I think it may be  Ctrl+Alt+K.

It never goes away. It just repeats incessantly every 15 seconds. Surely this gives a very bad impression for new users. Please can it be removed.

Observed with Raspberry Pi 1 Model B and current Raspberry Pi OS with desktop, Release date: January 11th 2021, Kernel version: 5.4. Steps to reproduce. Switch on the Raspberry Pi with a speaker connected to the headphone jack. 

Referrred to in the change log [here](https://github.com/raspberrypi-ui/piwiz/blob/master/debian/changelog).

**Comment by spl237** [comment]
Over the last year, we have done a lot of work to make Raspberry Pi more usable for those with visual impairments. A large part of this was to get a screen reader working, which allows audio prompts to be provided for the blind or partially-sighted, to enable them to use a desktop.

If we installed the screen reader by default, then *everything* would be read out on every system all the time - menus, window titles, window contents, controls. This is obviously not desirable - and I'm guessing you would find it even more irritating. However, it is not easy for someone who is visually impaired to work out how to install a screen reader, so we have added an easy keyboard shortcut to do so.

And in order for the visually-impared to find out about this shortcut, we have added *one* audio prompt to the first page of the first-run wizard. It only plays if the wizard is running, and until the user navigates off the first page. While you personally may find this irritating, perhaps you might like to consider that the intention is to make life easier for those less fortunate than yourself?

Getting rid of the audio prompt is trivial. Step through the wizard to the end, and you will never hear it again. If you can't be bothered to do that, press "Cancel" on the first page of the wizard and you will never hear it again. Or, in your situation, just don't use the version of RPiOS with the desktop; use the lite version - there's very little point in running a version of the OS with a desktop if you are not even able to see it; all the desktop will be doing is slowing your system down.

Most modern OSes include accessibility features, and voice prompts for enabling them are a standard part of first-run wizards. We will not be removing it.
