### ISSUE TITLE
PiWiz re-runs after apt update

### ISSUE THREAD

**Issue by RAdamMartin** [raspberrypi-ui/piwiz#19]
I recently updated my raspberry pi, and after the next restart, piwiz started blasting the prompt to enable screen reader, yet no window was visible one screen.  I killed the process, but I would not expect piwiz to re-run after an update, and I would expect it to force itself into the foreground on the desktop if it does.

Think the issue is the apt package overwrites some settings in autostart.

**Comment by spl237** [comment]
This has already been fixed - future updates should not cause the wizard to re-run. You would have seen the problem on this update because parts of the install scripts that ran on the update would have been from the older, un-fixed version of the package.
