### ISSUE TITLE
segfault if not root

### ISSUE THREAD

**Issue by maxnet** [raspberrypi-ui/piwiz#2]
If one accidentally starts piwiz without sudo (or it is unable to open files for writing for some other reason) it segfaults when you press "next".
May want to display a more graceful error message.

**Comment by spl237** [comment]
Piwiz should only ever run from boot on a clean image; it will therefore always run with sudo in response to the desktop autostart command.

I'll look into the segfault, but it's not a bug that is going to happen in the intended use.

**Comment by spl237** [comment]
I can't repeat this segfault - the wizard works as expected without sudo, albeit without making any changes to locale etc (as I would expect). Which particular page was it showing when you saw "next" resulting in a segfault?

**Comment by maxnet** [comment]
First one, may need to change country before pressing "next".

Segfaulted inside the fprintf() function that is called here: https://github.com/raspberrypi-ui/piwiz/blob/master/src/piwiz.c#L444
Due to fp being used that is NULL, because opening for writing failed

**Comment by spl237** [comment]
Thanks - now fixed (along with a couple of other places where I had forgotten to check the file pointer was valid...)
