### ISSUE TITLE
Unable to skip usercreation

### ISSUE THREAD

**Issue by andi34** [raspberrypi-ui/piwiz#26]
Hey!

I am using pi-gen to build a own PiOS image to my needs with a defined user and password. Sadly on first boot piwiz doesn't give the possibility to skip / hide this part of the setup.
If I purge piwiz from the image the network connection does not work.

pi-gen was modified here: https://github.com/RPi-Distro/pi-gen/commit/01b2432007766a6a1acc942f62d4ece7b25e560d
And 
https://github.com/RPi-Distro/pi-gen/commit/4de913c1fff28adde5681a5258978f6bfaa880b6

Any idea how to solve my problem?

Best regards

Andi

**Comment by spl237** [comment]
I'm afraid it is not possible to skip user creation in the wizard.

You can, however, preconfigure a user account when the card is flashed using Raspberry Pi Imager, or by putting a configuration file in the boot partition of a flashed image, as described on this page: https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/

**Comment by andi34** [comment]
Ok, but this means the changes made to pi-gen makes no sense or am I missing something?

**Comment by andi34** [comment]
Isn't there a command I can run on chroot while using pi gen to cancel/skip the rename?

**Comment by spl237** [comment]
In that case, your problem seems to be with pi-gen and not with piwiz, so I'd suggest asking the question on the pi-gen repo rather than here - I don't know enough about how pi-gen works to be able to comment.

**Comment by andi34** [comment]
We'll, from pi-gen I am able to skip 
```
SUDO_USER="${FIRST_USER_NAME}" rename-user -f -s
```
Is not executed.  I.could purge piwiz from the image, but then I am getting issues with the network not being configured... So I would need to solve that...

**Comment by andi34** [comment]
Just found that commit here: https://github.com/raspberrypi-ui/piwiz/commit/d0839a1558e574c53ab1d1ee18fad5a1a3c7927c

So in theory it's possible to skip it on piwiz.

**Comment by spl237** [comment]
You either need to preconfigure the image so the wizard doesn't run at all, or run the wizard, which will create a user. It's not going to be possible to modify the wizard to cope with your specific use-case.
