### ISSUE TITLE
Libreoffice always in English

### ISSUE THREAD

**Issue by maxnet** [raspberrypi-ui/piwiz#3]
You may want to consider also installing the non-English language packs for the applications you offer like Libreoffice, as right now one always gets an English user interface regardless of system language.

Other Linux distributions like Ubuntu and OpenSuSe do install language packs automatically, if user selects another language, so users kinda expect that.
Ubuntu offers a script called `check-language-support` (part of their language-selector-common package) that spits out the .deb package names one should install. You may be able to borrow that.

**Comment by spl237** [comment]
That's a good idea; I'll see if I can see what that script is doing.

**Comment by spl237** [comment]
Now implemented - will be in next release. Thanks for the suggestion!
