### ISSUE TITLE
Ask whether to download updates for capped web connections

### ISSUE THREAD

**Issue by gbaman** [raspberrypi-ui/piwiz#5]
Was just setting up a fresh Raspbian image there on a tethered 4G connection and was surprised to find the wizard go download updates without asking or a way to skip it. Once it started there was no way to easily stop it either (the X button didn't work and there was no cancel button)
Might it be worth displaying the total download size expected and asking permission before pulling down updates for folks on tethered or capped internet connections?

**Comment by ghollingworth** [comment]
We could add the capability of skipping the update, but we can't find out how much the update will download, (we've tried and there are a number of issues).

**Comment by gbaman** [comment]
Well, that would certainly at least be an improvement. Shame can't figure out beforehand how large the update is :(

**Comment by spl237** [comment]
There is a "skip" button on the update screen for this purpose already.

**Comment by spl237** [comment]
![skip](https://user-images.githubusercontent.com/10401149/43583177-9961a204-9656-11e8-881b-f75910ead7cd.jpg)

**Comment by gbaman** [comment]
I disagree @spl237, given the wording is 
"Press 'next' to check that Raspbian is up to date"
There is nothing here to say that if it isn't up to date, that a large amount of data could be downloaded (nor any way to cancel it once that fact has been realised). If it is a very out of date image, we could be talking numerous hundreds of mbs (if not even a gb).

I assumed by that language that it was going to do an apt update and then check with me before actually doing a full upgrade?

**Comment by gbaman** [comment]
That wording is a little better (assuming a newer version than is shipped with the June Raspbian copy which I have running in front of me), but I still think the wording sounds more like it is going to check for updates first as opposed to check for updates then download/apply them.

**Comment by spl237** [comment]
There is a skip button on the screen. This skips the upgrade. In version 0.2, there is even some more explicit text in the instruction - see above. I'm not sure what you are disagreeing with, given that the skip button exists and does what you want.
