### ISSUE TITLE
To resume #5

### ISSUE THREAD

**Issue by ZanderBrown** [raspberrypi-ui/piwiz#6]
And in danger of starting a small scale war:

Check for updates ≠ Download updates

Choosing next would imply checking, and *only* checking if updates exist

**Comment by ZanderBrown** [comment]
I believe @gbaman 's concern would be solved calling it 'Install updates' or similar instead

**Comment by gbaman** [comment]
A note that this could be a large download etc would be helpful as well yes as a warning for folks on capped internet connections (there are many), but yes @ZanderBrown is right, check for updates generally means apt update, not apt update and apt upgrade.
I think the ideal would be "Download and install updates" as that is clear then. (with the warning as well)

**Comment by spl237** [comment]
OK, I'll add a warning about the potential size of a download and tweak the wording on the window. (As Gordon pointed out earlier, it is non-trivial to calculate the size of a download with libpackagekit.)
